mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("noteit/", include("noteit.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
]

mysite/noteit/urls.py
from django.urls import path

from . import views

app_name = "noteit"
urlpatterns = [
    path("notes/folder/<str:folder>/", views.FolderIndexView.as_view(),
         name="folder_index"),

    path("notes/tag/<str:tag>/", views.TagIndexView.as_view(),
         name="folder_index"),

    # ex: noteit/notes/5/ --> edit note version (working)
    path("notes/<int:pk>/", views.DetailView.as_view(), name="detail"),

    # ex: noteit/5/results/ --> view note version (working)
    path("notes/<int:pk>/results/", views.ResultsView.as_view(),
         name="results"),

    # ex: noteit/5/delete --> delete note
    path("notes/<int:pk>/delete/", views.DeleteView.as_view(),
         name="delete_note"),

    # path("notes/<int:pk>/confirm-delete", views.ConfirmDelete.as_view(),
    #      name="confirm_delete"),

    # ex: noteit/5/submit/ --> submit edits to note (working)
    path("notes/<int:pk>/submit/", views.SubmitView.as_view(), name="submit"),

    # ex: noteit/notes --> index/homepage (working)
    path("notes/", views.IndexView.as_view(), name="index"),

    # ex: noteit/message --> javascript test (working)
    # path("notes/message", views.MessageView, name="message"),
]

mysite/noteit/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.forms import ModelForm


class Folder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Tag(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class NoteManager(models.Manager):
    def create_note(self, title, content, user):
        note = self.create(title=title, content=content, user=user)
        return note


class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=True, null=True, default="")
    content = models.TextField(max_length=10000, blank=True, null=True,
                               default="")
    # updates field when instance is created
    created_at = models.DateTimeField(auto_now_add=True)
    # updates field every time instance is saved
    updated_at = models.DateTimeField(auto_now=True)
    folder = models.ForeignKey(Folder, on_delete=models.SET_NULL,
                               blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    slug = models.SlugField(blank=True, null=True)
    objects = NoteManager()

    def __str__(self):
        return f"{self.title}: {self.content[0:50]}"

    def was_published_recently(self):
        return self.updated_at >= timezone.now() - datetime.timedelta(days=30)


class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ["title", "content"]

mysite/noteit/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from .models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=255)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

mysite/noteit/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.db import models
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.utils import timezone
# from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Note, User, Folder, Tag
# from .forms import LoginForm
# from django.middleware.csrf import CsrfViewMiddleware
import colorama

colorama.init()


def MessageView(x):
    return HttpResponse("Hello World!")


class IndexView(LoginRequiredMixin, generic.ListView):
    print("index runs")
    login_url = "/accounts/login/"
    # redirect_field_name = "redirect_to"

    template_name = "noteit/index.html"
    context_object_name = "latest_note_list"

    def get_queryset(self):
        print("index-get_queryset runs")
        """Return notes that user owns."""
        # username = get_username(request)
        # return Note.objects.filter(Note.user == username)
        return Note.objects.filter(user=self.request.user).order_by(
            "-updated_at")[
            :50
        ]

    def get_context_data(self, **kwargs):
        print("index-get_context runs")
        context = super().get_context_data(**kwargs)
        context['folders'] = Folder.objects.filter(user=self.request.user)
        return context

    def format_date(old_date):
        return old_date.strftime("%H:%M:%S")

    def post(self, request, *args, **kwargs):
        print("index-post runs")
        username = self.request.user
        text = request.POST.get('new-text')
        # User.objects.get(username="admin")
        note = Note.objects.create_note(title=text, content=text, user=username)
        note.save()
        new_id = note.id
        # context = {"title": "", "content": "", "user": admin_user,
        #            "note_id": new_id}

        return HttpResponseRedirect(f"/noteit/notes/{new_id}")
        # return render(request, f"noteit/{new_id}/detail.html", context)


class FolderIndexView(LoginRequiredMixin, generic.ListView):
    print("folder_index_view")
    login_url = "/accounts/login/"
    redirect_field_name = "redirect_to"
    template_name = "noteit/folder_index.html"
    context_object_name = "folder_note_list"
    model = Note

    def get_queryset(self):
        folder_name = self.kwargs.get('folder')
        folder = get_object_or_404(Folder, name=folder_name)
        return Note.objects.filter(user=self.request.user).filter(
            folder=folder)


class TagIndexView(LoginRequiredMixin, generic.ListView):
    print("tag_index_view")
    login_url = "/accounts/login/"
    redirect_field_name = "redirect_to"
    template_name = "noteit/tag_index.html"
    context_object_name = "tag_note_list"
    model = Note

    def get_queryset(self):
        tag_name = self.kwargs.get('tag')
        tag = get_object_or_404(Tag, name=tag_name)
        return Note.objects.filter(user=self.request.user).filter(
            tag=tag)


class DetailView(LoginRequiredMixin, generic.DetailView):
    print("detailView")
    login_url = "/accounts/login/"
    redirect_field_name = "redirect_to"

    model = Note
    content = models.TextField()
    template_name = "noteit/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Access Note object
        note = self.object
        # Access and manipulate updated_at attribute
        updated_at = note.updated_at
        updated_at_str = updated_at.strftime("%m.%d.%y_%H:%M")
        created_at = note.created_at
        created_at_str = created_at.strftime("%m.%d.%y_%H:%M")
        if note.tags.exists():
            tags = " | ".join(tag.name for tag in note.tags.all())
        else:
            tags = "None"
        # Pass manipulated value to context
        context['updated_at'] = updated_at_str
        context['created_at'] = created_at_str
        context['tags'] = tags
        return context


class ResultsView(LoginRequiredMixin, generic.DetailView):
    print("resultsView")
    login_url = "/accounts/login/"
    redirect_field_name = "redirect_to"

    model = Note
    content = Note.content
    template_name = "noteit/results.html"

class SubmitView(LoginRequiredMixin, generic.View):
    login_url = '/accounts/login/'
    print("submitView")

    def post(self, request, pk):
        note_instance = get_object_or_404(Note, pk=pk)
        form_data = request.POST
        note_instance.title = form_data['title']
        note_instance.content = form_data['content']
        note_instance.updated_at = timezone.localtime()
        note_instance.save()
        return HttpResponseRedirect(reverse(
            'noteit:index', args=()))

    def get(self, request, pk):
        note_instance = get_object_or_404(Note, pk=pk)
        return render(request, 'noteit/note_form.html', {'note': note_instance})


# class ConfirmDelete(generic.RedirectView):
#     template_name = 'noteit/index.html'


class DeleteView(LoginRequiredMixin, generic.DeleteView):
    print(colorama.Fore.GREEN + colorama.Back.BLACK + "delete_view")
    print(colorama.Style.RESET_ALL)

    model = Note
    login_url = "/accounts/login/"

    def get_queryset(self):
        print(colorama.Fore.GREEN + colorama.Back.BLACK +
              "delete get_queryset runs")
        print(colorama.Style.RESET_ALL)
        return super().get_queryset().filter(user=self.request.user)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        # return reverse('noteit:confirm_delete', kwargs={'pk': self.object.pk})
        return reverse('noteit:index')


def get_username(request):
    print("get_username runs")
    current_user = request.user
    if current_user.is_authenticated:
        username = current_user.username
    else:
        username = None
    return username

mysite/noteit/templates/noteit/base.html
<!doctype html>
{% load static %}
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>My base html page</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body class="m-2" style="margin:3%">
  <div class="nav1 row m-2">
    <div class="col-5" style="margin:2%">
        <a href="http://localhost:8000/noteit/notes" class="title3">
            <h1 class="nav2 title3 h1">noteit:_the_notes_app</h1>
        </a>
    </div>
    <div class="nav3 col-3 mt-2 pb-0">
        <p class="nav4 pt-3" style="font-size:small">User: {{ user.username }} <span class="nav6">x</span> <span class="nav7">|</span></p>
        <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button class="nav5" style="font-size:small" type="submit">logout</button>
        </form>
    </div>

  </div>
  {% if user.is_authenticated %}
    {% block content %}{% endblock %}
  {% else %}
    {% block content2 %}{% endblock %}
  {% endif %}
  </body>
</html>

{% block scripts %}
    <script>
        let delete_buttons = document.querySelectorAll(".delete-btn1");
        delete_buttons.forEach(button => {
            console.log("button", button);
            button.addEventListener("click", function(){
                let confirmation = confirm(`Are you sure you want to delete this item?`);
                if (confirmation) {
                    let form = this.closest("form");
                    form.submit();
                }
            });
        });
    </script>
{% endblock %}

mysite/noteit/templates/noteit/detail.html
{% extends 'noteit/base.html' %}

{% block content %}

<form action="{% url 'noteit:submit' note.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend class="legend1">
            <h3 class="legend2">edit your note</h3>
        </legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <ul style="list-style: none" class="ul1">
            <li class="li1 title1" style="font-size:medium">
                {% comment %} <label for: "title" class="title1"> {% endcomment %}
                <div class="title4" >
                    <input type="text" name="title" value="{{note.title}}" placeholder="title" class="title2">
                    <div class="submit2">
                        <input type="submit" value="submit" class="submit1">
                    </div>
                </div>
                <div class="title4">
                    <input type="text" name="folder" value={{tags}} class="title2" >
                    <div class="submit2">
                        <input type="submit" value="submit" class="submit1">
                    </div>
                </div>
                {% comment %} </label> {% endcomment %}
            </li>
            <li class="li1 li2">
                <textarea type="textarea" name="content" style="border:none; ;" class="textbox1 col-8" placeholder="text">{{note.content | default:""}}</textarea>
                <div class="info1 col-4 mr-6">
                    <div class="info2">
                        <h5>note details</h5>
                        <p>updated:<br><span class="info3"> {{ updated_at }} </span></p>
                        <p>created:<br><span class="info3"> {{ created_at }} </span></p>
                        <p>folder:<br><span class="info3"> {{ note.folder }} </span></p>
                        <p>tags:<br><span class="info3"> {{ tags }} </span></p>
                    </div>
                </div>
            </li>
        </ul>
    </fieldset>

</form>
{% endblock %}

mysite/noteit/templates/noteit/filtered_index.html
{% extends 'noteit/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">New Note</button>
</form>
<div>
    <h3>recent_notes:</h3>
    {% if latest_note_list %}
        <table class="table1">
            <tr>
                <th>title</th>
                <th></th>
                <th>content</th>
                <th></th>
                <th>updated</th>
                <th></th>
                <th>created</th>
            </tr>
        {% for note in latest_note_list %}
            <tr >
                <th class="row1">
                    <li style="text-align: left;">
                        <a href="{% url 'noteit:results' note.id %}" style="text-decoration: none;">{{ note.title }}</a></th>
                    </li>
                </th>
                <th class="row1">
                    <li style="list-style: none">
                        <span style="visibility: hidden"> --- </span>
                        <span class="dots1">...</span>
                        <span style="visibility: hidden"> --- </span>
                    </li>
                </th>
                <th class="row1" style="list-style: none; text-align: left; font-weight: 200;">
                    {{ note.content }}
                </th>
                <th class="row1">
                    <li style="list-style: none">
                        <span style="visibility: hidden"> --- </span>
                        <span class="dots1">...</span>
                        <span style="visibility: hidden"> --- </span>
                    </li>
                </th>
                <th class="row1">
                    <span style="font-size:smaller; font-weight: 200;"> {{note.updated_at|date:"n-j-y"}}
                    </span>
                </th>
                <th class="row1">
                    <li style="list-style: none">
                        <span style="visibility: hidden"> --- </span>
                        <span class="dots1">...</span>
                        <span style="visibility: hidden"> --- </span>
                    </li>
                </th>
                <th class="row1">
                    <span style="font-size:smaller; font-weight: 200;"> {{note.created_at|date:"n-j-y"}}
                </th>
            </tr>
        {% endfor %}
        </table>
        <div>
            <h3>folders:</h3>
            {% if folders %}
                <ul>
                {% for folder in folders %}
                    <li>{{ folder.name }}
                        <a href="{% url 'noteit:index' folder.id %}" style="text-decoration: none;">{{ folder.name }}</a>
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No folders available.</p>
            {% endif %}
        </div>
        <div>
            <h3>tags:</h3>
        </div>
    {% else %}
        <p>No notes are available.</p>
    {% endif %}
</div>

{% endblock %}

mysite/noteit/templates/noteit/folder_index.html
{% extends 'noteit/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">New Note</button>
</form>
<div>
    <h3>recent_notes:</h3>
    {% if folder_note_list %}
        <table class="table1">
            <tr>
                <th>title</th>
                <th></th>
                <th>content</th>
                <th></th>
                <th>updated</th>
                <th></th>
                <th>created</th>
            </tr>
        {% for note in folder_note_list %}
            <tr >
                <th class="row1">
                    <li style="text-align: left;">
                        <a href="{% url 'noteit:results' note.id %}" style="text-decoration: none;">{{ note.title }}</a></th>
                    </li>
                </th>
                <th class="row1">
                    <li style="list-style: none">
                        <span style="visibility: hidden"> --- </span>
                        <span class="dots1">...</span>
                        <span style="visibility: hidden"> --- </span>
                    </li>
                </th>
                <th class="row1" style="list-style: none; text-align: left; font-weight: 200;">
                    {{ note.content }}
                </th>
                <th class="row1">
                    <li style="list-style: none">
                        <span style="visibility: hidden"> --- </span>
                        <span class="dots1">...</span>
                        <span style="visibility: hidden"> --- </span>
                    </li>
                </th>
                <th class="row1">
                    <span style="font-size:smaller; font-weight: 200;"> {{note.updated_at|date:"n-j-y"}}
                    </span>
                </th>
                <th class="row1">
                    <li style="list-style: none">
                        <span style="visibility: hidden"> --- </span>
                        <span class="dots1">...</span>
                        <span style="visibility: hidden"> --- </span>
                    </li>
                </th>
                <th class="row1">
                    <span style="font-size:smaller; font-weight: 200;"> {{note.created_at|date:"n-j-y"}}
                </th>
            </tr>
        {% endfor %}
        </table>
        <div>
            <h3>tags:</h3>
        </div>
    {% else %}
        <p>No notes are available.</p>
    {% endif %}
</div>

{% endblock %}

mysite/noteit/templates/noteit/index.html
{% extends 'noteit/base.html' %}

{% block content %}
    <form method="post" class="new-note1">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="new-note2">new note</button>
        <input name="new-text" id="new-text" type="text" class="new-note3">
    </form>
    <div class="index-table1">
        <h3>recent_notes:</h3>
        {% if latest_note_list %}
            <table class="table1">
                <tr>
                    <th>title</th>
                    <th></th>
                    <th>content</th>
                    <th></th>
                    <th>updated</th>
                    <th></th>
                    <th>created</th>
                    <th></th>
                    <th>delete</th>
                </tr>
            {% for note in latest_note_list %}
                <tr >
                    <th class="row1">
                        <li style="text-align: left;">
                            <a href="{% url 'noteit:results' note.id %}"
                            style="text-decoration: none; font-weight:500;"
                            >{{ note.title | default:" - empty - " }}</a></th>
                        </li>
                    </th>
                    <th class="row1">
                        <li style="list-style: none">
                            <span style="visibility: hidden"> --- </span>
                            <span class="dots1">...</span>
                            <span style="visibility: hidden"> --- </span>
                        </li>
                    </th>
                    <th class="row1" style="list-style: none; text-align: left; font-weight: 200;">
                        <a href="{% url 'noteit:detail' note.id %}"
                        style="text-decoration: none; font-weight:500;"
                        >{{ note.content | default:" - empty - " }}</a>
                    </th>
                    <th class="row1">
                        <li style="list-style: none">
                            <span style="visibility: hidden"> --- </span>
                            <span class="dots1">...</span>
                            <span style="visibility: hidden"> --- </span>
                        </li>
                    </th>
                    <th class="row1">
                        <span style="font-size:smaller; font-weight: 200;"> {{note.updated_at|date:"n-j-y"}}
                        </span>
                    </th>
                    <th class="row1">
                        <li style="list-style: none">
                            <span style="visibility: hidden"> --- </span>
                            <span class="dots1">...</span>
                            <span style="visibility: hidden"> --- </span>
                        </li>
                    </th>
                    <th class="row1">
                        <span style="font-size:smaller; font-weight: 200;"> {{note.created_at|date:"n-j-y"}}
                    </th>
                    <th class="row1">
                        <li style="list-style: none">
                            <span style="visibility: hidden"> --- </span>
                            <span class="dots1">...</span>
                            <span style="visibility: hidden"> --- </span>
                        </li>
                    </th>
                    <th class="row1">
                        <span style="font-size:smaller; font-weight: 200;">
                        <form id="delete-form{{ note.id }}" action="{% url 'noteit:delete_note' pk=note.id %}" method="post">
                            {% csrf_token %}
                            <button type="button" class="delete-btn1">&#9744;</button>
                        </form>
                    </th>
                </tr>
            {% endfor %}
            </table>
            <div>
                <h3>folders:</h3>
                <form method="post" class="new-folder1">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="new-folder2">new folder</button>
                    <input name="new-folder-name" id="new-folder-id" type="text" class="new-folder3">
                </form>
                {% if folders %}
                    <table class="table1">
                    {% for folder in folders %}
                        <li>
                            <a href="{% url 'noteit:folder_index' folder.name %}" style="text-decoration: none;">{{ folder.name }}</a>
                        </li>
                    {% endfor %}
                    </table>
                {% else %}
                    <ul>
                        <li class="dash1">No folders available.</li>
                    </ul>
                {% endif %}
            </div>
            <div>
                <h3>tags:</h3>
                {% if tags %}
                <table>
                {% for tag in tags %}
                    <li>
                        <a href="{% url 'noteit:tag_index' tag.name %}" style="text-decoration: none;">{{ tag.name }}</a>
                    </li>
                {% endfor %}
                </table>
            {% else %}
                <table>
                    <li class="dash1">no tags available.</li>
                </table>
            {% endif %}
            </div>
        {% else %}
            <ul>
                <li class="dash1">no notes are available.</li>
            </ul>
        {% endif %}
    </div>
{% endblock %}

mysite/noteit/templates/noteit/login.html
{% extends 'noteit/base.html' %}

{% block content %}
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

{% block content2 %}
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/noteit/templates/noteit/new_note.html
{% extends 'noteit/base.html' %}

{% block content %}

<form action="{% url 'noteit:detail' note_id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h2>write your note</h2>
        </legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <ul style="list-style: none">
            <li>
                <label for: "title"> title:
                    <input type="text" name="title" value={self.object.title} style="border-top:none; border-left:none; border-right:none">
                </label>
            </li>
            <li style="padding-top:5%">
                <textarea type="textarea" name="content" value={self.object.contetn} style="border:none;" class="textbox1"></textarea>
            </li>
        </ul>
    </fieldset>
    <input type="submit" value="note">
    </form>
{% endblock %}

mysite/noteit/templates/noteit/results.html
{% extends 'noteit/base.html' %}
{% load static %}
{% block content %}
<legend>
    <ul style="list-style: none; padding:2%; border-left: 1px black solid;">
        <li style="font-size:large">title: {{ note.title }}</li>
        <li style="font-size:small">created: {{ note.created_at|date:"D n-j-y"}} at
            {{note.created_at|time:"P" }}</li>
        <li style="font-size:small">modified: {{ note.updated_at|date:"D n-j-y"}} at
            {{note.updated_at|time:"P" }}</li>
        <hr>
        <li class="li1 li2">
            <div class="textbox2 container-xl" style="float: left">
                <p class="textbox3" style="text-align: left; font-size: medium;">{{ note.content }}</p>
            </div>
            <div class="info1 container-sm" style="float: right">
                <div class="info2" style="font-size:small"">
                    <h4>note details</h4>
                    <p>updated:<br><span class="info3"> {{ note.updated_at }} </span></p>
                    <p>created:<br><span class="info3"> {{ note.created_at }} </span></p>
                    <p>folder:<br><span class="info3"> {{ note.folder }} </span></p>
                    <p>tags:B<br><span class="info3"> {{ note.tags }} </span></p>
                </div>
            </div>
        </li>
    </ul>
    <div>
        <a href="{% url 'noteit:detail' note.id %}" class="btn btn-light border-0"><button class="border-0 bg-light">edit note</button></a>
    </div>





</legend>
{% endblock %}

mysite/noteit/templates/noteit/tag_index.html
{% extends 'noteit/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">New Note</button>
</form>
<div>
    <h3>recent_notes:</h3>
    {% if tag_note_list %}
        <table class="table1">
            <tr>
                <th>title</th>
                <th></th>
                <th>content</th>
                <th></th>
                <th>updated</th>
                <th></th>
                <th>created</th>
            </tr>
        {% for note in tag_note_list %}
            <tr >
                <th class="row1">
                    <li style="text-align: left;">
                        <a href="{% url 'noteit:results' note.id %}" style="text-decoration: none;">{{ note.title }}</a></th>
                    </li>
                </th>
                <th class="row1">
                    <li style="list-style: none">
                        <span style="visibility: hidden"> --- </span>
                        <span class="dots1">...</span>
                        <span style="visibility: hidden"> --- </span>
                    </li>
                </th>
                <th class="row1" style="list-style: none; text-align: left; font-weight: 200;">
                    {{ note.content }}
                </th>
                <th class="row1">
                    <li style="list-style: none">
                        <span style="visibility: hidden"> --- </span>
                        <span class="dots1">...</span>
                        <span style="visibility: hidden"> --- </span>
                    </li>
                </th>
                <th class="row1">
                    <span style="font-size:smaller; font-weight: 200;"> {{note.updated_at|date:"n-j-y"}}
                    </span>
                </th>
                <th class="row1">
                    <li style="list-style: none">
                        <span style="visibility: hidden"> --- </span>
                        <span class="dots1">...</span>
                        <span style="visibility: hidden"> --- </span>
                    </li>
                </th>
                <th class="row1">
                    <span style="font-size:smaller; font-weight: 200;"> {{note.created_at|date:"n-j-y"}}
                </th>
            </tr>
        {% endfor %}
        </table>
        <div>
            <h3>tags:</h3>
        </div>
    {% else %}
        <p>No notes are available.</p>
    {% endif %}
</div>

{% endblock %}

mysite/noteit/templates/noteit/xx_confirm_delete.html
{% extends 'noteit/base.html' %}

{% block content %}
    <p>note deleted</p>
{% endblock %}

mysite/noteit/templates/noteit/xx_new_note.html
{% extends 'noteit/base.html' %}

{% block content %}

<form action="{% url 'noteit:detail' note_id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h2>write your note</h2>
        </legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <ul style="list-style: none">
            <li>
                <label for: "title"> title:
                    <input type="text" name="title" value={self.object.title} style="border-top:none; border-left:none; border-right:none">
                </label>
            </li>
            <li style="padding-top:5%">
                <textarea type="textarea" name="content" value={self.object.contetn} style="border:none;" class="textbox1"></textarea>
            </li>
        </ul>
    </fieldset>
    <input type="submit" value="note">
    </form>
{% endblock %}